import CDotFCCT.CTML.MixedRecordSystems

/-!
# Simultaneous function equations in the mixed model

This compatibility rule reuses the equations already generated by the type-only
alias compiler. Ordinary records remain recursion guards in the same model; these
function equations do not restrict the scalar or simultaneous record rules.
-/

set_option autoImplicit false

namespace CDotFCCT.CTML.Mixed

open CTMLCore CTMLCore.Syntax CTMLCore.Evaluation CTMLCore.Indexed

namespace System

variable (ghost : FieldName → Bool)

def operator {depth size : Nat} (system : RecursiveSystem depth size) (env : Environment)
    (selves : Nat → Fin size → Observation) (n : Nat) : Fin size → Observation :=
  fun index => interpret ghost (env.prepend fun index k => selves k index)
    (system.body index).raw n

def solution {depth size : Nat} (system : RecursiveSystem depth size)
    (env : Environment) : Nat → Fin size → Observation :=
  fixedPoint (operator ghost system env) (fun _ => (fun _ => False, fun _ => False))

def interpretation {depth size : Nat} (system : RecursiveSystem depth size)
    (env : Environment) (index : Fin size) : Indexed.Candidate :=
  fun n => solution ghost system env n index

def environment {depth size : Nat} (system : RecursiveSystem depth size)
    (env : Environment) : Environment := env.prepend (interpretation ghost system env)

variable {ghost}

theorem contractive {depth size : Nat} (system : RecursiveSystem depth size)
    (env : Environment) : Contractive (operator ghost system env) :=
  fun _ _ _ agree => funext fun index => arrow_congr
    (fun _ smaller => interpret_congr ghost (system.parameter index).raw
      (env.prepend_before agree smaller))
    (fun _ smaller => interpret_congr ghost (system.result index).raw
      (env.prepend_before agree smaller))

theorem unfold {depth size : Nat} (system : RecursiveSystem depth size)
    (env : Environment) (index : Fin size) (n : Nat) :
    interpretation ghost system env index n =
      interpret ghost (environment ghost system env) (system.body index).raw n :=
  congrFun (fixedPoint_unfold (contractive system env) _ n) index

theorem downward {depth size : Nat} (system : RecursiveSystem depth size)
    (env : Environment) (index : Fin size) :
    Downward (interpretation ghost system env index) := by
  intro m n within term
  rw [unfold system env index n, unfold system env index m]
  exact interpret_downward ghost (system.body index).raw _ m n within term

theorem equation {depth size : Nat} (system : RecursiveSystem depth size)
    (env : Environment) (index : Fin size) :
    interpret ghost (environment ghost system env) (system.name index).raw =
      interpret ghost (environment ghost system env) (system.body index).raw := by
  change prefixClosure ((environment ghost system env) index) = _
  simp only [environment, Environment.prepend, dite_eq_left index.isLt]
  exact (prefixClosure_eq (downward system env index)).trans
    (funext (unfold system env index))

theorem guards {depth size : Nat} (system : RecursiveSystem depth size)
    (env : Environment) (index : Fin size) (n : Nat) :
    interpretGuard ghost (environment ghost system env) (system.unfoldGuard index).raw n ∧
      interpretGuard ghost (environment ghost system env) (system.foldGuard index).raw n := by
  change Includes _ _ n ∧ Includes _ _ n
  rw [equation system env index]
  exact ⟨fun _ _ _ => ⟨id, id⟩, fun _ _ _ => ⟨id, id⟩⟩

/-- The solution validates the generated equations without strengthening outer assumptions. -/
theorem validates {size : Nat} {s : SubtypingContext} {env : Environment} {n : Nat}
    (system : RecursiveSystem s.typeDepth size) (valid : Validates ghost s env n) :
    Validates ghost (system.openContext s) (environment ghost system env) n := by
  intro guard membership
  rcases List.mem_append.mp membership with equation | outer
  · exact (List.mem_append.mp equation).elim
      (fun contains => match List.mem_ofFn.mp contains with
        | ⟨index, equal⟩ => equal ▸ (guards system env index n).1)
      (fun contains => match List.mem_ofFn.mp contains with
        | ⟨index, equal⟩ => equal ▸ (guards system env index n).2)
  obtain ⟨old, member, rfl⟩ := List.mem_map.mp outer
  exact congrFun (interpretGuard_liftAt ghost old.raw
    (env.prepend_lifted (interpretation ghost system env))) n ▸ valid old member

theorem noCollapse {size : Nat} (system : RecursiveSystem 0 size) :
    ¬ InvertingSubtype ghost (system.openContext SubtypingContext.empty)
      WFTy.top WFTy.bottom :=
  Mixed.noCollapse (validates system
    (empty_validates ghost (fun _ _ => (fun _ => False, fun _ => False)) 0))

end System

variable {ghost : FieldName → Bool}

/-- Close the existing alias compiler's whole recursive block under the mixed policy. -/
theorem Typing.recursiveSystem {size : Nat} {s : SubtypingContext}
    {context : TypingContext s.typeDepth} {term : Term} {type : WFTy s.typeDepth}
    (system : RecursiveSystem s.typeDepth size)
    (typing : Typing ghost (system.openContext s) (context.bindTypes size)
      (term.liftTy size) (type.weakenBy size)) :
    Typing ghost s context term type := by
  intro env n substitute valid valuation
  simpa only [System.environment, Ty.lift,
    interpret_liftAt ghost type.raw
      (env.prepend_lifted (System.interpretation ghost system env)),
    instantiate_liftTypes] using
    (show Computation (fun k =>
      (interpret ghost (System.environment ghost system env) (type.raw.lift size) k).1) n
      (instantiate (s.typeDepth + size) substitute (term.liftTy size)) from
        typing (System.environment ghost system env) n substitute
          (System.validates system valid) (valuation.bindTypes _))

end CDotFCCT.CTML.Mixed
